// Deterministic UIkit correctness check, driven entirely by the generated index.
// Nothing here encodes a class name from memory: every judgement is a lookup.
import fs from 'fs';
import { parse, anyClass, hasClass } from './parse.mjs';

const DEFAULT_INDEX = new URL('../index.json', import.meta.url);

// uk-width-1-2, uk-child-width-1-3@m, ... are generated by a LESS loop, so they
// appear in the CSS as a family rather than as an enumerable list of names.
const FRACTION = /^uk-(width|child-width)-([1-6]-[1-6]|auto|expand|fit|initial|small|medium|large|xlarge|xxlarge|max-(small|medium|large|xlarge|xxlarge)|min-(small|medium|large|xlarge|xxlarge))(@(s|m|l|xl))?$/;

// Containers whose children are laid out by the component itself, so uk-child-width-*
// on them is correct without a uk-grid attribute.
const CHILD_WIDTH_HOSTS = ['uk-slider-items', 'uk-slideshow-items', 'uk-lightbox-items',
  'uk-thumbnav', 'uk-dotnav', 'uk-subnav', 'uk-navbar-nav', 'uk-flex', 'uk-grid', 'uk-tab'];
const COLUMN_PARENTS = /^uk-(grid|flex|nav|subnav|slider-items|slideshow-items|thumbnav|dotnav|navbar)/;

// Surfaces that already declare --uk-inverse themselves; adding uk-light is redundant.
const AUTO_INVERSE = ['uk-section-primary', 'uk-section-secondary', 'uk-tile-primary',
  'uk-tile-secondary', 'uk-card-primary', 'uk-card-secondary', 'uk-overlay-primary', 'uk-offcanvas-bar'];

const ICON_ATTRS = ['uk-icon', 'uk-navbar-toggle-icon', 'uk-search-icon', 'uk-close',
  'uk-slidenav-next', 'uk-slidenav-previous', 'uk-overlay-icon', 'uk-marker', 'uk-spinner',
  'uk-totop', 'uk-pagination-next', 'uk-pagination-previous', 'uk-nav-parent-icon',
  'uk-drop-parent-icon', 'uk-navbar-parent-icon', 'uk-accordion-icon'];

const REINVENTS = [/display\s*:\s*flex/i, /display\s*:\s*grid/i, /grid-template-columns/i,
  /\bmargin\b/i, /\bpadding\b/i, /text-align/i, /@media/i, /justify-content/i, /align-items/i];
const FOREIGN = /(^|\s)(col-(xs|sm|md|lg)-\d|row$|btn(-|$)|container-fluid|d-flex|card-header|navbar-brand|grid-cols-\d|mx-auto|px-\d|py-\d|font-bold)/;

/** Levenshtein, small inputs only. */
function distance(a, b) {
  if (a === b) return 0;
  if (!a.length || !b.length) return Math.max(a.length, b.length);
  let prev = [...Array(b.length + 1).keys()];
  for (let i = 1; i <= a.length; i++) {
    const row = [i];
    for (let j = 1; j <= b.length; j++) {
      row[j] = Math.min(prev[j] + 1, row[j - 1] + 1, prev[j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1));
    }
    prev = row;
  }
  return prev[b.length];
}

export function loadIndex(path = DEFAULT_INDEX) {
  return JSON.parse(fs.readFileSync(path, 'utf8'));
}

export function makeChecker(index = loadIndex()) {
  const known = new Set(index.classes);
  const icons = new Set(index.icons);
  const attrs = new Set([...Object.keys(index.components), ...index.hookAttrs]);
  // how many components share each option name — used to surface distinctive ones
  const rarity = {};
  for (const def of Object.values(index.components)) for (const p of new Set(def.props)) rarity[p] = (rarity[p] ?? 0) + 1;

  const resolvable = (c) => {
    const base = c.replace(/@(s|m|l|xl)$/, '');
    return known.has(c) || known.has(base) || FRACTION.test(c) ||
      index.families.some((f) => c.startsWith(f) || base.startsWith(f));
  };

  /** Nearest valid names for a name that does not exist — makes the message actionable. */
  const suggest = (bad, limit = 3) => {
    const stem = bad.replace(/@(s|m|l|xl)$/, '');
    const parts = stem.split('-');
    const scored = [];
    for (const c of known) {
      const p = c.split('-');
      let shared = 0;
      while (shared < parts.length && shared < p.length && parts[shared] === p[shared]) shared++;
      if (shared < 2) continue;
      // among classes in the same family, prefer the closest tail
      scored.push([c, shared * 1000 - distance(parts.slice(shared).join('-'), p.slice(shared).join('-'))]);
    }
    return scored.sort((a, b) => b[1] - a[1]).slice(0, limit).map(([c]) => c);
  };

  return function check(html, { fragment = false, file = '<stdin>', requires = [] } = {}) {
    const doc = parse(html);
    const V = [];
    const add = (code, weight, detail, fix) => V.push({ code, weight, detail, fix });

    // --- 1. names that do not exist ---------------------------------------
    const seenCls = new Set(), seenAttr = new Set();
    for (const n of doc.nodes) {
      for (const c of n.classes) {
        if (!c.startsWith('uk-')) continue;
        if (/@(sm|md|lg|xs|xxl)$/.test(c)) {
          add('bad_breakpoint', 3, c, `UIkit has only @s @m @l @xl — did you mean ${c.replace(/@\w+$/, '@m')}?`);
        } else if (!resolvable(c) && !seenCls.has(c)) {
          seenCls.add(c);
          const s = suggest(c);
          add('invented_class', 3, c, s.length ? `no such class; real ones nearby: ${s.join(', ')}` : 'no such class');
        }
      }
      for (const [name, value] of Object.entries(n.attrs)) {
        if (!name.startsWith('uk-')) continue;
        if (!attrs.has(name)) {
          if (seenAttr.has(name)) continue;
          seenAttr.add(name);
          const isClass = resolvable(name);
          add('invented_attr', 3, name, isClass
            ? `${name} is a class, not a component — put it in class="" instead`
            : 'no component registers this attribute');
          continue;
        }
        const comp = index.components[name];
        if (comp?.props.length && value.includes(':')) {
          for (const pair of value.split(';')) {
            const k = pair.split(':')[0].trim();
            if (!k || /^(https?|\/\/)/.test(k)) continue;
            const camel = k.replace(/-([a-z])/g, (_, x) => x.toUpperCase());
            if (!comp.props.includes(camel) && !comp.args.includes(camel)) {
              // show the options that are distinctive to this component first —
              // every component has animation/duration/offset, few have `counter`
              const distinctive = [...comp.props].sort((a, b) => (rarity[a] ?? 99) - (rarity[b] ?? 99));
              add('invented_option', 2, `${name}="${k}: …"`,
                `${name} accepts: ${distinctive.slice(0, 12).join(', ')}`);
            }
          }
        }
      }
      const iv = n.attrs['uk-icon'];
      if (iv != null) {
        const m = iv.match(/icon\s*:\s*([a-z0-9-]+)/) || (/^[a-z0-9-]+$/.test(iv.trim()) ? [, iv.trim()] : null);
        if (m && !icons.has(m[1])) {
          const near = [...icons].filter((i) => i.includes(m[1].split('-')[0])).slice(0, 4);
          add('invented_icon', 2, m[1], near.length ? `no such icon; try ${near.join(', ')}` : 'no such icon');
        }
      }
    }

    // --- 2. structure -------------------------------------------------------
    for (const n of doc.nodes) {
      if (hasClass(n, 'uk-grid') && !('uk-grid' in n.attrs)) {
        add('grid_class_no_attr', 1, n.classes.join(' '),
          'uk-grid must be the attribute (<div uk-grid>) — as a bare class it never gets its gutters or row wrapping');
      }
      if (anyClass(n, /^uk-child-width-/) && !('uk-grid' in n.attrs) &&
          !CHILD_WIDTH_HOSTS.some((c) => hasClass(n, c))) {
        add('child_width_no_grid', 3, n.classes.join(' '), 'uk-child-width-* needs the uk-grid attribute on the same element');
      }
      if (anyClass(n, /^uk-width-\d-\d/) && n.parent && n.parent.tag !== 'body') {
        const cols = n.parent.children.filter((s) => anyClass(s, /^uk-width-\d-\d/));
        const ok = 'uk-grid' in n.parent.attrs || n.parent.classes.some((c) => COLUMN_PARENTS.test(c));
        if (cols.length > 1 && !ok) {
          add('width_without_grid', 3, `${cols.length} columns under <${n.parent.tag}>`,
            'columns need a uk-grid parent, otherwise they sit flush with no gutters');
        }
      }
      if (hasClass(n, 'uk-light') && AUTO_INVERSE.some((c) => hasClass(n, c))) {
        add('redundant_uk_light', 0.5, n.classes.join(' '),
          'this surface already sets --uk-inverse: light; uk-light is only for arbitrary dark backgrounds');
      }
      if ('uk-modal' in n.attrs && !doc.descendants(n).some((d) => hasClass(d, 'uk-modal-dialog'))) {
        add('modal_no_dialog', 2, 'uk-modal without .uk-modal-dialog', 'wrap the content in <div class="uk-modal-dialog">');
      }
      const toggle = n.attrs['uk-toggle'];
      if (toggle != null) {
        const sel = (toggle.match(/target\s*:\s*([^;]+)/) || [, toggle])[1]?.trim();
        if (sel?.startsWith('#') && !doc.byId.has(sel.slice(1))) {
          add('dangling_target', 2, sel, 'uk-toggle points at an id that does not exist on the page');
        }
      }
    }

    // --- 3. rebuilding what UIkit already ships ----------------------------
    if (doc.styleText.trim()) {
      const hits = REINVENTS.filter((r) => r.test(doc.styleText)).length;
      const lines = doc.styleText.trim().split('\n').length;
      if (hits) {
        add('custom_css_reinvents_utility', Math.min(hits, 4), `${hits} utility-covered properties`,
          'spacing, flex, grid, alignment and breakpoints all have uk-* utilities');
      }
      add('custom_css_lines', +Math.min(lines / 40, 3).toFixed(2), `${lines} lines of custom CSS`);
    }
    const inline = doc.nodes.filter((n) => /margin|padding|display|text-align|width\s*:\s*\d+%|flex/i.test(n.attrs.style ?? ''));
    if (inline.length) add('inline_style_over_utility', Math.min(inline.length, 5), `${inline.length} elements`, 'use uk-margin-* / uk-padding-* / uk-width-* instead');
    for (const n of doc.nodes) {
      const other = n.classes.filter((c) => !c.startsWith('uk-')).join(' ');
      if (other && FOREIGN.test(` ${other}`)) {
        add('foreign_framework_class', 2, other, 'Bootstrap/Tailwind class in a UIkit page');
        break;
      }
    }

    // --- 4. asset wiring ----------------------------------------------------
    if (!fragment) {
      const src = doc.scriptSrc.join(' ');
      if (!/uikit(\.min)?\.css/.test(doc.stylesheets.join(' '))) add('missing_uikit_css', 3, '(none)', 'link uikit.min.css');
      if (!/\buikit(\.min)?\.js/.test(src)) add('missing_uikit_js', 3, '(none)', 'load uikit.min.js');
      const usesIcons = doc.nodes.some((n) => ICON_ATTRS.some((a) => a in n.attrs) || anyClass(n, /^uk-icon/));
      if (usesIcons && !/uikit-icons(\.min)?\.js/.test(src)) {
        add('missing_icons_js', 3, 'icons used, uikit-icons.js not loaded', 'without it every icon renders empty');
      }
      if (!doc.nodes.some((n) => hasClass(n, 'uk-container') || anyClass(n, /^uk-section/))) {
        add('no_container', 1, 'no uk-container / uk-section wrapper');
      }
    }

    // --- 5. capability (eval only) -----------------------------------------
    const missed = requires.filter((r) => !new RegExp(r.re).test(html));
    for (const r of missed) add('missed_capability', 3, r.why);

    return {
      file,
      penalty: +V.reduce((s, v) => s + v.weight, 0).toFixed(2),
      capability: requires.length ? +((requires.length - missed.length) / requires.length).toFixed(2) : null,
      violations: V,
    };
  };
}
